# Generated by Django 3.1.6 on 2021-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('item01', models.CharField(default='', max_length=50)),
                ('item02', models.CharField(blank=True, default='', max_length=50)),
                ('item03', models.CharField(blank=True, default='', max_length=50)),
                ('item04', models.CharField(blank=True, default='', max_length=50)),
                ('item05', models.CharField(blank=True, default='', max_length=50)),
                ('item06', models.CharField(blank=True, default='', max_length=50)),
                ('item07', models.CharField(blank=True, default='', max_length=50)),
                ('item08', models.CharField(blank=True, default='', max_length=50)),
                ('item09', models.CharField(blank=True, default='', max_length=50)),
                ('item10', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
